//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2015-01-17 10:28:15 AM
namespace AdventureWorksODataDemo.AdventureWorksService
{
    
    /// <summary>
    /// There are no comments for AdventureWorksEntities in the schema.
    /// </summary>
    public partial class AdventureWorksEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new AdventureWorksEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AdventureWorksEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "AdventureWorksModel", "AdventureWorksODataDemo.AdventureWorksService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("AdventureWorksODataDemo.AdventureWorksService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("AdventureWorksModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ManufacturingInstructions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<vManufacturingInstructions> ManufacturingInstructions
        {
            get
            {
                if ((this._ManufacturingInstructions == null))
                {
                    this._ManufacturingInstructions = base.CreateQuery<vManufacturingInstructions>("ManufacturingInstructions");
                }
                return this._ManufacturingInstructions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<vManufacturingInstructions> _ManufacturingInstructions;
        /// <summary>
        /// There are no comments for WorkOrderRouting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<vWorkOrderRouting> WorkOrderRouting
        {
            get
            {
                if ((this._WorkOrderRouting == null))
                {
                    this._WorkOrderRouting = base.CreateQuery<vWorkOrderRouting>("WorkOrderRouting");
                }
                return this._WorkOrderRouting;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<vWorkOrderRouting> _WorkOrderRouting;
        /// <summary>
        /// There are no comments for ProductCatalog in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<vProductCatalog> ProductCatalog
        {
            get
            {
                if ((this._ProductCatalog == null))
                {
                    this._ProductCatalog = base.CreateQuery<vProductCatalog>("ProductCatalog");
                }
                return this._ProductCatalog;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<vProductCatalog> _ProductCatalog;
        /// <summary>
        /// There are no comments for CompanySales in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<vCompanySales> CompanySales
        {
            get
            {
                if ((this._CompanySales == null))
                {
                    this._CompanySales = base.CreateQuery<vCompanySales>("CompanySales");
                }
                return this._CompanySales;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<vCompanySales> _CompanySales;
        /// <summary>
        /// There are no comments for TerritorySalesDrilldown in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<vTerritorySalesDrilldown> TerritorySalesDrilldown
        {
            get
            {
                if ((this._TerritorySalesDrilldown == null))
                {
                    this._TerritorySalesDrilldown = base.CreateQuery<vTerritorySalesDrilldown>("TerritorySalesDrilldown");
                }
                return this._TerritorySalesDrilldown;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<vTerritorySalesDrilldown> _TerritorySalesDrilldown;
        /// <summary>
        /// There are no comments for ManufacturingInstructions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToManufacturingInstructions(vManufacturingInstructions vManufacturingInstructions)
        {
            base.AddObject("ManufacturingInstructions", vManufacturingInstructions);
        }
        /// <summary>
        /// There are no comments for WorkOrderRouting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToWorkOrderRouting(vWorkOrderRouting vWorkOrderRouting)
        {
            base.AddObject("WorkOrderRouting", vWorkOrderRouting);
        }
        /// <summary>
        /// There are no comments for ProductCatalog in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProductCatalog(vProductCatalog vProductCatalog)
        {
            base.AddObject("ProductCatalog", vProductCatalog);
        }
        /// <summary>
        /// There are no comments for CompanySales in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCompanySales(vCompanySales vCompanySales)
        {
            base.AddObject("CompanySales", vCompanySales);
        }
        /// <summary>
        /// There are no comments for TerritorySalesDrilldown in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTerritorySalesDrilldown(vTerritorySalesDrilldown vTerritorySalesDrilldown)
        {
            base.AddObject("TerritorySalesDrilldown", vTerritorySalesDrilldown);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"AdventureWorksModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/" +
                "edm\"><EntityType Name=\"vManufacturingInstructions\"><Key><PropertyRef Name=\"ID\" /" +
                "></Key><Property Name=\"ProductModelID\" Type=\"Edm.Int32\" Nullable=\"false\" p6:Stor" +
                "eGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/" +
                "edm/annotation\" /><Property Name=\"ProductName\" Type=\"Edm.String\" Nullable=\"false" +
                "\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Instructio" +
                "ns\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Prop" +
                "erty Name=\"LocationID\" Type=\"Edm.Int32\" /><Property Name=\"SetupHours\" Type=\"Edm." +
                "Decimal\" Precision=\"9\" Scale=\"4\" /><Property Name=\"MachineHours\" Type=\"Edm.Decim" +
                "al\" Precision=\"9\" Scale=\"4\" /><Property Name=\"LaborHours\" Type=\"Edm.Decimal\" Pre" +
                "cision=\"9\" Scale=\"4\" /><Property Name=\"LotSize\" Type=\"Edm.Int32\" /><Property Nam" +
                "e=\"Step\" Type=\"Edm.String\" MaxLength=\"1024\" FixedLength=\"false\" Unicode=\"true\" /" +
                "><Property Name=\"ID\" Type=\"Edm.Int64\" Nullable=\"false\" /></EntityType><EntityTyp" +
                "e Name=\"vWorkOrderRouting\"><Key><PropertyRef Name=\"ID\" /></Key><Property Name=\"W" +
                "orkOrderID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ProductID\" Type=" +
                "\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ProductNumber\" Type=\"Edm.String\" " +
                "Nullable=\"false\" MaxLength=\"25\" FixedLength=\"false\" Unicode=\"true\" /><Property N" +
                "ame=\"ProductName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=" +
                "\"false\" Unicode=\"true\" /><Property Name=\"OperationSequence\" Type=\"Edm.Int16\" Nul" +
                "lable=\"false\" /><Property Name=\"LocationID\" Type=\"Edm.Int16\" Nullable=\"false\" />" +
                "<Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLen" +
                "gth=\"false\" Unicode=\"true\" /><Property Name=\"ScheduledStartDate\" Type=\"Edm.DateT" +
                "ime\" Nullable=\"false\" Precision=\"3\" /><Property Name=\"ActualStartDate\" Type=\"Edm" +
                ".DateTime\" Precision=\"3\" /><Property Name=\"ScheduledEndDate\" Type=\"Edm.DateTime\"" +
                " Nullable=\"false\" Precision=\"3\" /><Property Name=\"ActualEndDate\" Type=\"Edm.DateT" +
                "ime\" Precision=\"3\" /><Property Name=\"ActualResourceHrs\" Type=\"Edm.Decimal\" Preci" +
                "sion=\"9\" Scale=\"4\" /><Property Name=\"PlannedCost\" Type=\"Edm.Decimal\" Nullable=\"f" +
                "alse\" Precision=\"19\" Scale=\"4\" /><Property Name=\"ActualCost\" Type=\"Edm.Decimal\" " +
                "Precision=\"19\" Scale=\"4\" /><Property Name=\"OrderQty\" Type=\"Edm.Int32\" Nullable=\"" +
                "false\" /><Property Name=\"ScrappedQty\" Type=\"Edm.Int16\" Nullable=\"false\" /><Prope" +
                "rty Name=\"DueDate\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /><Propert" +
                "y Name=\"ScrapReasonID\" Type=\"Edm.Int16\" /><Property Name=\"ScrapReason\" Type=\"Edm" +
                ".String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ID\"" +
                " Type=\"Edm.Int64\" Nullable=\"false\" /></EntityType><EntityType Name=\"vProductCata" +
                "log\"><Key><PropertyRef Name=\"ID\" /></Key><Property Name=\"ThumbNailPhoto\" Type=\"E" +
                "dm.Stream\" Nullable=\"false\" /><Property Name=\"LargePhoto\" Type=\"Edm.Stream\" Null" +
                "able=\"false\" /><Property Name=\"ProductID\" Type=\"Edm.Int32\" Nullable=\"false\" /><P" +
                "roperty Name=\"ProductNumber\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"25\" F" +
                "ixedLength=\"false\" Unicode=\"true\" /><Property Name=\"ProductName\" Type=\"Edm.Strin" +
                "g\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Propert" +
                "y Name=\"ProductModel\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLen" +
                "gth=\"false\" Unicode=\"true\" /><Property Name=\"ProductCategory\" Type=\"Edm.String\" " +
                "Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property N" +
                "ame=\"ProductSubcategory\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" Fixed" +
                "Length=\"false\" Unicode=\"true\" /><Property Name=\"Description\" Type=\"Edm.String\" N" +
                "ullable=\"false\" MaxLength=\"400\" FixedLength=\"false\" Unicode=\"true\" /><Property N" +
                "ame=\"CultureID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"6\" FixedLength=\"tr" +
                "ue\" Unicode=\"true\" /><Property Name=\"Color\" Type=\"Edm.String\" MaxLength=\"15\" Fix" +
                "edLength=\"false\" Unicode=\"true\" /><Property Name=\"Size\" Type=\"Edm.String\" MaxLen" +
                "gth=\"5\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Weight\" Type=\"Edm.D" +
                "ecimal\" Precision=\"8\" Scale=\"2\" /><Property Name=\"ListPrice\" Type=\"Edm.Decimal\" " +
                "Nullable=\"false\" Precision=\"19\" Scale=\"4\" /><Property Name=\"ID\" Type=\"Edm.Int64\"" +
                " Nullable=\"false\" /></EntityType><EntityType Name=\"vCompanySales\"><Key><Property" +
                "Ref Name=\"ID\" /></Key><Property Name=\"ProductCategory\" Type=\"Edm.String\" Nullabl" +
                "e=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Pr" +
                "oductSubCategory\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=" +
                "\"false\" Unicode=\"true\" /><Property Name=\"OrderYear\" Type=\"Edm.Int32\" /><Property" +
                " Name=\"OrderQtr\" Type=\"Edm.String\" MaxLength=\"31\" FixedLength=\"false\" Unicode=\"t" +
                "rue\" /><Property Name=\"Sales\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" /><Pro" +
                "perty Name=\"ID\" Type=\"Edm.Int64\" Nullable=\"false\" /></EntityType><EntityType Nam" +
                "e=\"vTerritorySalesDrilldown\"><Key><PropertyRef Name=\"ID\" /></Key><Property Name=" +
                "\"TerritoryName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"f" +
                "alse\" Unicode=\"true\" /><Property Name=\"SalesPersonID\" Type=\"Edm.Int32\" Nullable=" +
                "\"false\" /><Property Name=\"EmployeeFirstName\" Type=\"Edm.String\" Nullable=\"false\" " +
                "MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"EmployeeLast" +
                "Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"SalesOrderNumber\" Type=\"Edm.String\" Nullable=\"false" +
                "\" MaxLength=\"25\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Total\" Typ" +
                "e=\"Edm.Decimal\" Nullable=\"false\" Precision=\"19\" Scale=\"4\" /><Property Name=\"ID\" " +
                "Type=\"Edm.Int64\" Nullable=\"false\" /></EntityType></Schema><Schema Namespace=\"Mic" +
                "rosoft.Samples.SqlServer.AdventureWorksService\" xmlns=\"http://schemas.microsoft." +
                "com/ado/2009/11/edm\"><EntityContainer Name=\"AdventureWorksEntities\" m:IsDefaultE" +
                "ntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://schemas.micr" +
                "osoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"ManufacturingInstructions" +
                "\" EntityType=\"AdventureWorksModel.vManufacturingInstructions\" /><EntitySet Name=" +
                "\"WorkOrderRouting\" EntityType=\"AdventureWorksModel.vWorkOrderRouting\" /><EntityS" +
                "et Name=\"ProductCatalog\" EntityType=\"AdventureWorksModel.vProductCatalog\" /><Ent" +
                "itySet Name=\"CompanySales\" EntityType=\"AdventureWorksModel.vCompanySales\" /><Ent" +
                "itySet Name=\"TerritorySalesDrilldown\" EntityType=\"AdventureWorksModel.vTerritory" +
                "SalesDrilldown\" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.vManufacturingInstructions in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ManufacturingInstructions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class vManufacturingInstructions : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new vManufacturingInstructions object.
        /// </summary>
        /// <param name="productModelID">Initial value of ProductModelID.</param>
        /// <param name="productName">Initial value of ProductName.</param>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static vManufacturingInstructions CreatevManufacturingInstructions(int productModelID, string productName, long ID)
        {
            vManufacturingInstructions vManufacturingInstructions = new vManufacturingInstructions();
            vManufacturingInstructions.ProductModelID = productModelID;
            vManufacturingInstructions.ProductName = productName;
            vManufacturingInstructions.ID = ID;
            return vManufacturingInstructions;
        }
        /// <summary>
        /// There are no comments for Property ProductModelID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductModelID
        {
            get
            {
                return this._ProductModelID;
            }
            set
            {
                this.OnProductModelIDChanging(value);
                this._ProductModelID = value;
                this.OnProductModelIDChanged();
                this.OnPropertyChanged("ProductModelID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductModelID;
        partial void OnProductModelIDChanging(int value);
        partial void OnProductModelIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
                this.OnPropertyChanged("ProductName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property Instructions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Instructions
        {
            get
            {
                return this._Instructions;
            }
            set
            {
                this.OnInstructionsChanging(value);
                this._Instructions = value;
                this.OnInstructionsChanged();
                this.OnPropertyChanged("Instructions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Instructions;
        partial void OnInstructionsChanging(string value);
        partial void OnInstructionsChanged();
        /// <summary>
        /// There are no comments for Property LocationID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> LocationID
        {
            get
            {
                return this._LocationID;
            }
            set
            {
                this.OnLocationIDChanging(value);
                this._LocationID = value;
                this.OnLocationIDChanged();
                this.OnPropertyChanged("LocationID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _LocationID;
        partial void OnLocationIDChanging(global::System.Nullable<int> value);
        partial void OnLocationIDChanged();
        /// <summary>
        /// There are no comments for Property SetupHours in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> SetupHours
        {
            get
            {
                return this._SetupHours;
            }
            set
            {
                this.OnSetupHoursChanging(value);
                this._SetupHours = value;
                this.OnSetupHoursChanged();
                this.OnPropertyChanged("SetupHours");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _SetupHours;
        partial void OnSetupHoursChanging(global::System.Nullable<decimal> value);
        partial void OnSetupHoursChanged();
        /// <summary>
        /// There are no comments for Property MachineHours in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> MachineHours
        {
            get
            {
                return this._MachineHours;
            }
            set
            {
                this.OnMachineHoursChanging(value);
                this._MachineHours = value;
                this.OnMachineHoursChanged();
                this.OnPropertyChanged("MachineHours");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _MachineHours;
        partial void OnMachineHoursChanging(global::System.Nullable<decimal> value);
        partial void OnMachineHoursChanged();
        /// <summary>
        /// There are no comments for Property LaborHours in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> LaborHours
        {
            get
            {
                return this._LaborHours;
            }
            set
            {
                this.OnLaborHoursChanging(value);
                this._LaborHours = value;
                this.OnLaborHoursChanged();
                this.OnPropertyChanged("LaborHours");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _LaborHours;
        partial void OnLaborHoursChanging(global::System.Nullable<decimal> value);
        partial void OnLaborHoursChanged();
        /// <summary>
        /// There are no comments for Property LotSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> LotSize
        {
            get
            {
                return this._LotSize;
            }
            set
            {
                this.OnLotSizeChanging(value);
                this._LotSize = value;
                this.OnLotSizeChanged();
                this.OnPropertyChanged("LotSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _LotSize;
        partial void OnLotSizeChanging(global::System.Nullable<int> value);
        partial void OnLotSizeChanged();
        /// <summary>
        /// There are no comments for Property Step in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Step
        {
            get
            {
                return this._Step;
            }
            set
            {
                this.OnStepChanging(value);
                this._Step = value;
                this.OnStepChanged();
                this.OnPropertyChanged("Step");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Step;
        partial void OnStepChanging(string value);
        partial void OnStepChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.vWorkOrderRouting in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("WorkOrderRouting")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class vWorkOrderRouting : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new vWorkOrderRouting object.
        /// </summary>
        /// <param name="workOrderID">Initial value of WorkOrderID.</param>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="productNumber">Initial value of ProductNumber.</param>
        /// <param name="productName">Initial value of ProductName.</param>
        /// <param name="operationSequence">Initial value of OperationSequence.</param>
        /// <param name="locationID">Initial value of LocationID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="scheduledStartDate">Initial value of ScheduledStartDate.</param>
        /// <param name="scheduledEndDate">Initial value of ScheduledEndDate.</param>
        /// <param name="plannedCost">Initial value of PlannedCost.</param>
        /// <param name="orderQty">Initial value of OrderQty.</param>
        /// <param name="scrappedQty">Initial value of ScrappedQty.</param>
        /// <param name="dueDate">Initial value of DueDate.</param>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static vWorkOrderRouting CreatevWorkOrderRouting(int workOrderID, int productID, string productNumber, string productName, short operationSequence, short locationID, string name, global::System.DateTime scheduledStartDate, global::System.DateTime scheduledEndDate, decimal plannedCost, int orderQty, short scrappedQty, global::System.DateTime dueDate, long ID)
        {
            vWorkOrderRouting vWorkOrderRouting = new vWorkOrderRouting();
            vWorkOrderRouting.WorkOrderID = workOrderID;
            vWorkOrderRouting.ProductID = productID;
            vWorkOrderRouting.ProductNumber = productNumber;
            vWorkOrderRouting.ProductName = productName;
            vWorkOrderRouting.OperationSequence = operationSequence;
            vWorkOrderRouting.LocationID = locationID;
            vWorkOrderRouting.Name = name;
            vWorkOrderRouting.ScheduledStartDate = scheduledStartDate;
            vWorkOrderRouting.ScheduledEndDate = scheduledEndDate;
            vWorkOrderRouting.PlannedCost = plannedCost;
            vWorkOrderRouting.OrderQty = orderQty;
            vWorkOrderRouting.ScrappedQty = scrappedQty;
            vWorkOrderRouting.DueDate = dueDate;
            vWorkOrderRouting.ID = ID;
            return vWorkOrderRouting;
        }
        /// <summary>
        /// There are no comments for Property WorkOrderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int WorkOrderID
        {
            get
            {
                return this._WorkOrderID;
            }
            set
            {
                this.OnWorkOrderIDChanging(value);
                this._WorkOrderID = value;
                this.OnWorkOrderIDChanged();
                this.OnPropertyChanged("WorkOrderID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _WorkOrderID;
        partial void OnWorkOrderIDChanging(int value);
        partial void OnWorkOrderIDChanged();
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
                this.OnPropertyChanged("ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductNumber
        {
            get
            {
                return this._ProductNumber;
            }
            set
            {
                this.OnProductNumberChanging(value);
                this._ProductNumber = value;
                this.OnProductNumberChanged();
                this.OnPropertyChanged("ProductNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductNumber;
        partial void OnProductNumberChanging(string value);
        partial void OnProductNumberChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
                this.OnPropertyChanged("ProductName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property OperationSequence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short OperationSequence
        {
            get
            {
                return this._OperationSequence;
            }
            set
            {
                this.OnOperationSequenceChanging(value);
                this._OperationSequence = value;
                this.OnOperationSequenceChanged();
                this.OnPropertyChanged("OperationSequence");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _OperationSequence;
        partial void OnOperationSequenceChanging(short value);
        partial void OnOperationSequenceChanged();
        /// <summary>
        /// There are no comments for Property LocationID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short LocationID
        {
            get
            {
                return this._LocationID;
            }
            set
            {
                this.OnLocationIDChanging(value);
                this._LocationID = value;
                this.OnLocationIDChanged();
                this.OnPropertyChanged("LocationID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _LocationID;
        partial void OnLocationIDChanging(short value);
        partial void OnLocationIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ScheduledStartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ScheduledStartDate
        {
            get
            {
                return this._ScheduledStartDate;
            }
            set
            {
                this.OnScheduledStartDateChanging(value);
                this._ScheduledStartDate = value;
                this.OnScheduledStartDateChanged();
                this.OnPropertyChanged("ScheduledStartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ScheduledStartDate;
        partial void OnScheduledStartDateChanging(global::System.DateTime value);
        partial void OnScheduledStartDateChanged();
        /// <summary>
        /// There are no comments for Property ActualStartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ActualStartDate
        {
            get
            {
                return this._ActualStartDate;
            }
            set
            {
                this.OnActualStartDateChanging(value);
                this._ActualStartDate = value;
                this.OnActualStartDateChanged();
                this.OnPropertyChanged("ActualStartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ActualStartDate;
        partial void OnActualStartDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnActualStartDateChanged();
        /// <summary>
        /// There are no comments for Property ScheduledEndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ScheduledEndDate
        {
            get
            {
                return this._ScheduledEndDate;
            }
            set
            {
                this.OnScheduledEndDateChanging(value);
                this._ScheduledEndDate = value;
                this.OnScheduledEndDateChanged();
                this.OnPropertyChanged("ScheduledEndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ScheduledEndDate;
        partial void OnScheduledEndDateChanging(global::System.DateTime value);
        partial void OnScheduledEndDateChanged();
        /// <summary>
        /// There are no comments for Property ActualEndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ActualEndDate
        {
            get
            {
                return this._ActualEndDate;
            }
            set
            {
                this.OnActualEndDateChanging(value);
                this._ActualEndDate = value;
                this.OnActualEndDateChanged();
                this.OnPropertyChanged("ActualEndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ActualEndDate;
        partial void OnActualEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnActualEndDateChanged();
        /// <summary>
        /// There are no comments for Property ActualResourceHrs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> ActualResourceHrs
        {
            get
            {
                return this._ActualResourceHrs;
            }
            set
            {
                this.OnActualResourceHrsChanging(value);
                this._ActualResourceHrs = value;
                this.OnActualResourceHrsChanged();
                this.OnPropertyChanged("ActualResourceHrs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _ActualResourceHrs;
        partial void OnActualResourceHrsChanging(global::System.Nullable<decimal> value);
        partial void OnActualResourceHrsChanged();
        /// <summary>
        /// There are no comments for Property PlannedCost in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal PlannedCost
        {
            get
            {
                return this._PlannedCost;
            }
            set
            {
                this.OnPlannedCostChanging(value);
                this._PlannedCost = value;
                this.OnPlannedCostChanged();
                this.OnPropertyChanged("PlannedCost");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _PlannedCost;
        partial void OnPlannedCostChanging(decimal value);
        partial void OnPlannedCostChanged();
        /// <summary>
        /// There are no comments for Property ActualCost in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> ActualCost
        {
            get
            {
                return this._ActualCost;
            }
            set
            {
                this.OnActualCostChanging(value);
                this._ActualCost = value;
                this.OnActualCostChanged();
                this.OnPropertyChanged("ActualCost");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _ActualCost;
        partial void OnActualCostChanging(global::System.Nullable<decimal> value);
        partial void OnActualCostChanged();
        /// <summary>
        /// There are no comments for Property OrderQty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OrderQty
        {
            get
            {
                return this._OrderQty;
            }
            set
            {
                this.OnOrderQtyChanging(value);
                this._OrderQty = value;
                this.OnOrderQtyChanged();
                this.OnPropertyChanged("OrderQty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OrderQty;
        partial void OnOrderQtyChanging(int value);
        partial void OnOrderQtyChanged();
        /// <summary>
        /// There are no comments for Property ScrappedQty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short ScrappedQty
        {
            get
            {
                return this._ScrappedQty;
            }
            set
            {
                this.OnScrappedQtyChanging(value);
                this._ScrappedQty = value;
                this.OnScrappedQtyChanged();
                this.OnPropertyChanged("ScrappedQty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _ScrappedQty;
        partial void OnScrappedQtyChanging(short value);
        partial void OnScrappedQtyChanged();
        /// <summary>
        /// There are no comments for Property DueDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DueDate
        {
            get
            {
                return this._DueDate;
            }
            set
            {
                this.OnDueDateChanging(value);
                this._DueDate = value;
                this.OnDueDateChanged();
                this.OnPropertyChanged("DueDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DueDate;
        partial void OnDueDateChanging(global::System.DateTime value);
        partial void OnDueDateChanged();
        /// <summary>
        /// There are no comments for Property ScrapReasonID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> ScrapReasonID
        {
            get
            {
                return this._ScrapReasonID;
            }
            set
            {
                this.OnScrapReasonIDChanging(value);
                this._ScrapReasonID = value;
                this.OnScrapReasonIDChanged();
                this.OnPropertyChanged("ScrapReasonID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _ScrapReasonID;
        partial void OnScrapReasonIDChanging(global::System.Nullable<short> value);
        partial void OnScrapReasonIDChanged();
        /// <summary>
        /// There are no comments for Property ScrapReason in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ScrapReason
        {
            get
            {
                return this._ScrapReason;
            }
            set
            {
                this.OnScrapReasonChanging(value);
                this._ScrapReason = value;
                this.OnScrapReasonChanged();
                this.OnPropertyChanged("ScrapReason");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ScrapReason;
        partial void OnScrapReasonChanging(string value);
        partial void OnScrapReasonChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.vProductCatalog in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ProductCatalog")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class vProductCatalog : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new vProductCatalog object.
        /// </summary>
        /// <param name="thumbNailPhoto">Initial value of ThumbNailPhoto.</param>
        /// <param name="largePhoto">Initial value of LargePhoto.</param>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="productNumber">Initial value of ProductNumber.</param>
        /// <param name="productName">Initial value of ProductName.</param>
        /// <param name="productModel">Initial value of ProductModel.</param>
        /// <param name="productCategory">Initial value of ProductCategory.</param>
        /// <param name="productSubcategory">Initial value of ProductSubcategory.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="cultureID">Initial value of CultureID.</param>
        /// <param name="listPrice">Initial value of ListPrice.</param>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static vProductCatalog CreatevProductCatalog(global::System.Data.Services.Client.DataServiceStreamLink thumbNailPhoto, global::System.Data.Services.Client.DataServiceStreamLink largePhoto, int productID, string productNumber, string productName, string productModel, string productCategory, string productSubcategory, string description, string cultureID, decimal listPrice, long ID)
        {
            vProductCatalog vProductCatalog = new vProductCatalog();
            vProductCatalog.ThumbNailPhoto = thumbNailPhoto;
            vProductCatalog.LargePhoto = largePhoto;
            vProductCatalog.ProductID = productID;
            vProductCatalog.ProductNumber = productNumber;
            vProductCatalog.ProductName = productName;
            vProductCatalog.ProductModel = productModel;
            vProductCatalog.ProductCategory = productCategory;
            vProductCatalog.ProductSubcategory = productSubcategory;
            vProductCatalog.Description = description;
            vProductCatalog.CultureID = cultureID;
            vProductCatalog.ListPrice = listPrice;
            vProductCatalog.ID = ID;
            return vProductCatalog;
        }
        /// <summary>
        /// There are no comments for Property ThumbNailPhoto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceStreamLink ThumbNailPhoto
        {
            get
            {
                return this._ThumbNailPhoto;
            }
            set
            {
                this.OnThumbNailPhotoChanging(value);
                this._ThumbNailPhoto = value;
                this.OnThumbNailPhotoChanged();
                this.OnPropertyChanged("ThumbNailPhoto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceStreamLink _ThumbNailPhoto;
        partial void OnThumbNailPhotoChanging(global::System.Data.Services.Client.DataServiceStreamLink value);
        partial void OnThumbNailPhotoChanged();
        /// <summary>
        /// There are no comments for Property LargePhoto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceStreamLink LargePhoto
        {
            get
            {
                return this._LargePhoto;
            }
            set
            {
                this.OnLargePhotoChanging(value);
                this._LargePhoto = value;
                this.OnLargePhotoChanged();
                this.OnPropertyChanged("LargePhoto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceStreamLink _LargePhoto;
        partial void OnLargePhotoChanging(global::System.Data.Services.Client.DataServiceStreamLink value);
        partial void OnLargePhotoChanged();
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
                this.OnPropertyChanged("ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductNumber
        {
            get
            {
                return this._ProductNumber;
            }
            set
            {
                this.OnProductNumberChanging(value);
                this._ProductNumber = value;
                this.OnProductNumberChanged();
                this.OnPropertyChanged("ProductNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductNumber;
        partial void OnProductNumberChanging(string value);
        partial void OnProductNumberChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
                this.OnPropertyChanged("ProductName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property ProductModel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductModel
        {
            get
            {
                return this._ProductModel;
            }
            set
            {
                this.OnProductModelChanging(value);
                this._ProductModel = value;
                this.OnProductModelChanged();
                this.OnPropertyChanged("ProductModel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductModel;
        partial void OnProductModelChanging(string value);
        partial void OnProductModelChanged();
        /// <summary>
        /// There are no comments for Property ProductCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductCategory
        {
            get
            {
                return this._ProductCategory;
            }
            set
            {
                this.OnProductCategoryChanging(value);
                this._ProductCategory = value;
                this.OnProductCategoryChanged();
                this.OnPropertyChanged("ProductCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductCategory;
        partial void OnProductCategoryChanging(string value);
        partial void OnProductCategoryChanged();
        /// <summary>
        /// There are no comments for Property ProductSubcategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductSubcategory
        {
            get
            {
                return this._ProductSubcategory;
            }
            set
            {
                this.OnProductSubcategoryChanging(value);
                this._ProductSubcategory = value;
                this.OnProductSubcategoryChanged();
                this.OnPropertyChanged("ProductSubcategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductSubcategory;
        partial void OnProductSubcategoryChanging(string value);
        partial void OnProductSubcategoryChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CultureID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CultureID
        {
            get
            {
                return this._CultureID;
            }
            set
            {
                this.OnCultureIDChanging(value);
                this._CultureID = value;
                this.OnCultureIDChanged();
                this.OnPropertyChanged("CultureID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CultureID;
        partial void OnCultureIDChanging(string value);
        partial void OnCultureIDChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this._Color = value;
                this.OnColorChanged();
                this.OnPropertyChanged("Color");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Color;
        partial void OnColorChanging(string value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for Property Size in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this.OnSizeChanging(value);
                this._Size = value;
                this.OnSizeChanged();
                this.OnPropertyChanged("Size");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Size;
        partial void OnSizeChanging(string value);
        partial void OnSizeChanged();
        /// <summary>
        /// There are no comments for Property Weight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Weight
        {
            get
            {
                return this._Weight;
            }
            set
            {
                this.OnWeightChanging(value);
                this._Weight = value;
                this.OnWeightChanged();
                this.OnPropertyChanged("Weight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Weight;
        partial void OnWeightChanging(global::System.Nullable<decimal> value);
        partial void OnWeightChanged();
        /// <summary>
        /// There are no comments for Property ListPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this.OnListPriceChanging(value);
                this._ListPrice = value;
                this.OnListPriceChanged();
                this.OnPropertyChanged("ListPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _ListPrice;
        partial void OnListPriceChanging(decimal value);
        partial void OnListPriceChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.vCompanySales in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CompanySales")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class vCompanySales : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new vCompanySales object.
        /// </summary>
        /// <param name="productCategory">Initial value of ProductCategory.</param>
        /// <param name="productSubCategory">Initial value of ProductSubCategory.</param>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static vCompanySales CreatevCompanySales(string productCategory, string productSubCategory, long ID)
        {
            vCompanySales vCompanySales = new vCompanySales();
            vCompanySales.ProductCategory = productCategory;
            vCompanySales.ProductSubCategory = productSubCategory;
            vCompanySales.ID = ID;
            return vCompanySales;
        }
        /// <summary>
        /// There are no comments for Property ProductCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductCategory
        {
            get
            {
                return this._ProductCategory;
            }
            set
            {
                this.OnProductCategoryChanging(value);
                this._ProductCategory = value;
                this.OnProductCategoryChanged();
                this.OnPropertyChanged("ProductCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductCategory;
        partial void OnProductCategoryChanging(string value);
        partial void OnProductCategoryChanged();
        /// <summary>
        /// There are no comments for Property ProductSubCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductSubCategory
        {
            get
            {
                return this._ProductSubCategory;
            }
            set
            {
                this.OnProductSubCategoryChanging(value);
                this._ProductSubCategory = value;
                this.OnProductSubCategoryChanged();
                this.OnPropertyChanged("ProductSubCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductSubCategory;
        partial void OnProductSubCategoryChanging(string value);
        partial void OnProductSubCategoryChanged();
        /// <summary>
        /// There are no comments for Property OrderYear in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> OrderYear
        {
            get
            {
                return this._OrderYear;
            }
            set
            {
                this.OnOrderYearChanging(value);
                this._OrderYear = value;
                this.OnOrderYearChanged();
                this.OnPropertyChanged("OrderYear");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _OrderYear;
        partial void OnOrderYearChanging(global::System.Nullable<int> value);
        partial void OnOrderYearChanged();
        /// <summary>
        /// There are no comments for Property OrderQtr in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OrderQtr
        {
            get
            {
                return this._OrderQtr;
            }
            set
            {
                this.OnOrderQtrChanging(value);
                this._OrderQtr = value;
                this.OnOrderQtrChanged();
                this.OnPropertyChanged("OrderQtr");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OrderQtr;
        partial void OnOrderQtrChanging(string value);
        partial void OnOrderQtrChanged();
        /// <summary>
        /// There are no comments for Property Sales in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Sales
        {
            get
            {
                return this._Sales;
            }
            set
            {
                this.OnSalesChanging(value);
                this._Sales = value;
                this.OnSalesChanged();
                this.OnPropertyChanged("Sales");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Sales;
        partial void OnSalesChanging(global::System.Nullable<decimal> value);
        partial void OnSalesChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksModel.vTerritorySalesDrilldown in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TerritorySalesDrilldown")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class vTerritorySalesDrilldown : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new vTerritorySalesDrilldown object.
        /// </summary>
        /// <param name="territoryName">Initial value of TerritoryName.</param>
        /// <param name="salesPersonID">Initial value of SalesPersonID.</param>
        /// <param name="employeeFirstName">Initial value of EmployeeFirstName.</param>
        /// <param name="employeeLastName">Initial value of EmployeeLastName.</param>
        /// <param name="salesOrderNumber">Initial value of SalesOrderNumber.</param>
        /// <param name="total">Initial value of Total.</param>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static vTerritorySalesDrilldown CreatevTerritorySalesDrilldown(string territoryName, int salesPersonID, string employeeFirstName, string employeeLastName, string salesOrderNumber, decimal total, long ID)
        {
            vTerritorySalesDrilldown vTerritorySalesDrilldown = new vTerritorySalesDrilldown();
            vTerritorySalesDrilldown.TerritoryName = territoryName;
            vTerritorySalesDrilldown.SalesPersonID = salesPersonID;
            vTerritorySalesDrilldown.EmployeeFirstName = employeeFirstName;
            vTerritorySalesDrilldown.EmployeeLastName = employeeLastName;
            vTerritorySalesDrilldown.SalesOrderNumber = salesOrderNumber;
            vTerritorySalesDrilldown.Total = total;
            vTerritorySalesDrilldown.ID = ID;
            return vTerritorySalesDrilldown;
        }
        /// <summary>
        /// There are no comments for Property TerritoryName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TerritoryName
        {
            get
            {
                return this._TerritoryName;
            }
            set
            {
                this.OnTerritoryNameChanging(value);
                this._TerritoryName = value;
                this.OnTerritoryNameChanged();
                this.OnPropertyChanged("TerritoryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TerritoryName;
        partial void OnTerritoryNameChanging(string value);
        partial void OnTerritoryNameChanged();
        /// <summary>
        /// There are no comments for Property SalesPersonID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SalesPersonID
        {
            get
            {
                return this._SalesPersonID;
            }
            set
            {
                this.OnSalesPersonIDChanging(value);
                this._SalesPersonID = value;
                this.OnSalesPersonIDChanged();
                this.OnPropertyChanged("SalesPersonID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SalesPersonID;
        partial void OnSalesPersonIDChanging(int value);
        partial void OnSalesPersonIDChanged();
        /// <summary>
        /// There are no comments for Property EmployeeFirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmployeeFirstName
        {
            get
            {
                return this._EmployeeFirstName;
            }
            set
            {
                this.OnEmployeeFirstNameChanging(value);
                this._EmployeeFirstName = value;
                this.OnEmployeeFirstNameChanged();
                this.OnPropertyChanged("EmployeeFirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmployeeFirstName;
        partial void OnEmployeeFirstNameChanging(string value);
        partial void OnEmployeeFirstNameChanged();
        /// <summary>
        /// There are no comments for Property EmployeeLastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmployeeLastName
        {
            get
            {
                return this._EmployeeLastName;
            }
            set
            {
                this.OnEmployeeLastNameChanging(value);
                this._EmployeeLastName = value;
                this.OnEmployeeLastNameChanged();
                this.OnPropertyChanged("EmployeeLastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmployeeLastName;
        partial void OnEmployeeLastNameChanging(string value);
        partial void OnEmployeeLastNameChanged();
        /// <summary>
        /// There are no comments for Property SalesOrderNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SalesOrderNumber
        {
            get
            {
                return this._SalesOrderNumber;
            }
            set
            {
                this.OnSalesOrderNumberChanging(value);
                this._SalesOrderNumber = value;
                this.OnSalesOrderNumberChanged();
                this.OnPropertyChanged("SalesOrderNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SalesOrderNumber;
        partial void OnSalesOrderNumberChanging(string value);
        partial void OnSalesOrderNumberChanged();
        /// <summary>
        /// There are no comments for Property Total in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Total
        {
            get
            {
                return this._Total;
            }
            set
            {
                this.OnTotalChanging(value);
                this._Total = value;
                this.OnTotalChanged();
                this.OnPropertyChanged("Total");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Total;
        partial void OnTotalChanging(decimal value);
        partial void OnTotalChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
